"""
digest.py - Weekly Digest Generator for The Load Bench
Combines component and forum data into a formatted markdown newsletter digest.
"""

import os
import logging
from datetime import date
from typing import Dict, List, Optional

logger = logging.getLogger(__name__)


def format_stock_status(in_stock: Optional[bool]) -> str:
    """Return a human-readable stock status."""
    if in_stock is True:
        return "✅ In Stock"
    elif in_stock is False:
        return "❌ Out of Stock"
    else:
        return "❓ Check Site"


def format_component_section(components: Dict[str, List[Dict]]) -> str:
    """Format the component availability section."""
    in_stock_items = []
    watching_items = []
    check_items = []

    for category, items in components.items():
        for item in items:
            note = item.get("note", "")
            in_stock = item.get("in_stock")
            name = item.get("name", "Unknown")
            price = item.get("price", "N/A")
            url = item.get("url", "")
            source = item.get("source", "")

            line = f"- **{name}** — {price or 'price unknown'} | [{source}]({url})"

            if note:
                check_items.append(f"{line} *(check manually)*")
            elif in_stock is True:
                in_stock_items.append(line)
            elif in_stock is False:
                watching_items.append(line)
            else:
                check_items.append(line)

    sections = []

    if in_stock_items:
        sections.append("### In Stock This Week\n\n" + "\n".join(in_stock_items))
    else:
        sections.append("### In Stock This Week\n\n*No confirmed in-stock items found this run — verify manually.*")

    if watching_items:
        sections.append("### Watching (Out of Stock / Check for Restocks)\n\n" + "\n".join(watching_items))

    if check_items:
        sections.append("### Needs Manual Check\n\n" + "\n".join(check_items))

    return "\n\n".join(sections)


def format_reddit_section(reddit_data: Dict[str, List[Dict]]) -> str:
    """Format the Reddit trending posts section."""
    if not reddit_data:
        return "*No Reddit data available this week.*"

    lines = []
    for subreddit, posts in reddit_data.items():
        if not posts:
            continue
        lines.append(f"#### r/{subreddit}\n")
        for post in posts[:5]:  # top 5 per sub
            title = post.get("title", "Untitled")
            score = post.get("score", 0)
            url = post.get("url", "#")
            num_comments = post.get("num_comments", 0)
            top_comment = post.get("top_comment", "")

            lines.append(f"- **[{title}]({url})** — ⬆️ {score} | 💬 {num_comments} comments")
            if top_comment:
                preview = top_comment[:150].replace("\n", " ")
                lines.append(f"  > *Top comment:* \"{preview}...\"")
        lines.append("")

    return "\n".join(lines) if lines else "*No Reddit data available this week.*"


def format_snipers_hide_section(sh_data: List[Dict]) -> str:
    """Format the Sniper's Hide threads section."""
    if not sh_data:
        return "*No Sniper's Hide data available this week.*"

    lines = []
    for thread in sh_data[:10]:
        title = thread.get("title", "Unknown thread")
        url = thread.get("url", "#")
        replies = thread.get("replies", "")
        last_activity = thread.get("last_activity", "")
        note = thread.get("note", "")

        line = f"- **[{title}]({url})**"
        if replies and replies != "unknown" and replies != "N/A":
            line += f" — {replies}"
        if last_activity and last_activity != "unknown" and last_activity != "N/A":
            line += f" *(last activity: {last_activity})*"
        if note:
            line += f" ⚠️ {note}"
        lines.append(line)

    return "\n".join(lines) if lines else "*No Sniper's Hide data available this week.*"


def generate_digest(components: Dict, forums: Dict, output_dir: str = "output") -> str:
    """
    Generate the weekly markdown digest.
    Returns the path to the saved file.
    """
    today = date.today().isoformat()
    filename = f"weekly-{today}.md"
    os.makedirs(output_dir, exist_ok=True)
    filepath = os.path.join(output_dir, filename)

    reddit_data = forums.get("reddit", {})
    snipers_hide_data = forums.get("snipers_hide", [])

    component_section = format_component_section(components)
    reddit_section = format_reddit_section(reddit_data)
    sh_section = format_snipers_hide_section(snipers_hide_data)

    # Count stats for header
    total_components = sum(len(v) for v in components.values())
    total_reddit = sum(len(v) for v in reddit_data.values())
    total_sh = len(snipers_hide_data)

    digest = f"""# The Load Bench — Weekly Digest {today}

> Auto-generated by the scraper pipeline. Review and add personal notes before sending.
> Stats: {total_components} component records | {total_reddit} Reddit posts | {total_sh} Sniper's Hide threads

---

## 🔍 Component Availability

{component_section}

---

## 💬 From the Community

### Trending on Reddit

{reddit_section}

### Sniper's Hide Buzz

{sh_section}

---

## 📝 Next Steps

*James — add your personal load bench notes here before sending:*

- [ ] Current load development update (caliber, powder, bullet, results)
- [ ] Any range trip or competition results worth sharing
- [ ] Reader questions or responses to highlight
- [ ] Upcoming content/video ideas
- [ ] Any deals or restocks worth flagging to subscribers

---

*Generated by The Load Bench scraper pipeline. [Source code](https://github.com/crashtest22/theloadbench/tree/main/scraper)*
"""

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(digest)

    logger.info(f"Digest saved to: {filepath}")
    return filepath


if __name__ == "__main__":
    # Test with empty data
    test_components = {"powders": [], "primers": [], "brass": [], "bullets": []}
    test_forums = {"reddit": {}, "snipers_hide": []}
    path = generate_digest(test_components, test_forums)
    print(f"Test digest written to: {path}")
